spring.application.name=reserva-service
server.port=8084

# Conexión a Eureka 
eureka.client.service-url.defaultZone=${EUREKA_URI:http://discovery-server:8761/eureka/}

# Configuración del Circuit Breaker
resilience4j.circuitbreaker.instances.reservaCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.reservaCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.reservaCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.reservaCB.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.reservaCB.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.reservaCB.failureRateThreshold=50

# Configuración Swagger
springdoc.api-docs.path=/v3/api-docs

# Configuración PostgreSQL
# Configuración PostgreSQL para Docker
spring.datasource.url=jdbc:postgresql://postgres-db:5432/hotel_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_hotel}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_hotel}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${spring.application.name}