# 1. Nombre para identificarlo en la red
spring.application.name=discovery-server

# 2. El puerto estándar por convención para Eureka
server.port=8761

# 3. No queremos que el servidor se registre a sí mismo como un "cliente"
eureka.client.register-with-eureka=false

# 4. No queremos que el servidor intente "descargar" la lista de otros (él es el dueño)
eureka.client.fetch-registry=false

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${spring.application.name}